# $r^{3}Y^{3}_\mu(\Omega)$ operator expansion in $SU(3)$ tensors

$$
\left[r^{3}_{\sigma}Y^{3}_\mu(\hat{r}_{\sigma})\right]_{\hspace{7mm}M_{J_o}}^{L_o=J_o=3} 
= \sum_{\eta,l,m_l,\eta',l',m_{l'},m_s,m_{s'}}\Big\langle \eta',l',m_{l'},\frac{1}{2},m_{s'}\Big| r^{3}_{\sigma}Y^{3}_\mu(\hat{r}_{\sigma}) \Big| \eta,l,m_{l},\frac{1}{2},m_{s} \Big\rangle a^{\dagger}_{l',m_{l'},\frac{1}{2},m_{s'}}a_{l,m_l,\frac{1}{2},m_{s}}
\\ = \sum_{\eta,l,m_l,\eta',l',m_{l'},m_s,m_{s'}}
\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle 
\langle l,m_l; 3,\mu | l',m_{l'} \rangle
\langle \frac{1}{2},m_s; 0,0 | \frac{1}{2},m_{s'} \rangle 
a^{\dagger}_{l',m_{l'},\frac{1}{2},m_{s'}}a_{l,m_l,\frac{1}{2},m_{s}}
\\ = \sum_{\eta,l,m_l,\eta',l',m_{l'},m_s,m_{s'}}
\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle 
(-1)^{l-m_l}\frac{\sqrt{2l'+1}}{\sqrt{7}}\langle l',m_{l'}; l,-m_l | 1,\mu \rangle 
(-1)^{\frac{1}{2}-m_s}\sqrt{2}\langle  \frac{1}{2},m_{s'}; \frac{1}{2},-m_s | 0,0  \rangle 
a^{\dagger}_{l',m_{l'},\frac{1}{2},m_{s'}}a_{l,m_l,\frac{1}{2},m_{s}}
\\ = \sum_{\eta,l,m_l,\eta',l',m_{l'},m_s,m_{s'}}
(-1)^{\eta}\sqrt{2(2l'+1)}\frac{\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle}{\sqrt{7}}
\langle l',m_{l'}; l,-m_l | 3,\mu \rangle 
\langle  \frac{1}{2},m_{s'}; \frac{1}{2},-m_s | 0,0  \rangle
a^{\dagger}_{(\eta',0),l',m_{l'},\frac{1}{2},m_{s'}}\tilde{a}_{(0,\eta),l,-m_l,\frac{1}{2},-m_{s}}
\\ = \sum_{\eta,l,\eta',l'}
(-1)^{\eta}\sqrt{\frac{2(2l'+1)}{7}}\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle
\Big\{a^{\dagger}_{(\eta',0),l',\frac{1}{2}}\tilde{a}_{(0,\eta),l,\frac{1}{2}}\Big\}^{L_o=J_o=3}_{\hspace{7mm}M_{J_o}}
\\=\sqrt{\frac{2}{7}}\sum_{(\lambda_o, \mu_o),k_o,\eta,l,\eta',l'}(-1)^{\eta}\sqrt{2l'+1}\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle \langle (\eta',0),0,l'; (0,\eta),0,l||(\lambda_o,\mu_o),k_o,3 \rangle_{\rho_o=1}\\\times\Big\{a^{\dagger}_{(\eta',0)\frac{1}{2}}\times \tilde{a}_{(0,\eta)\frac{1}{2}}\Big\}^{\rho_o=1(\lambda_o,\mu_o)k_oL_o=J_o=3}_{\hspace{26mm}M_{J_o}}
$$

A result to keep in mind in order to check the reduced matrix elements is

$$
\Big\langle \eta',l',\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle = (-1)^{l-l'}\sqrt{\frac{2l+1}{2l'+1}}\Big\langle \eta,l,\frac{1}{2}\Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta',l',\frac{1}{2}\Big\rangle$$

# Program to compute $r^{3}Y^{3}_\mu(\Omega)$ operator expansion in $SU(3)$ tensors for actinides

The expansion is given by

$$\left[r^{3}_{\sigma}Y^{3}_\mu(\hat{r}_{\sigma})\right]_{\hspace{7mm}M_{J_o}}^{L_o=J_o=3} = \sqrt{\frac{2}{7}}\sum_{(\lambda_o,\mu_o)k_o}\sum_{l,l',\eta,\eta'}(-1)^{\eta}\sqrt{2l'+1}\Big\langle \eta',l',\frac{1}{2} \Big|\Big| r^{3}_{\sigma}Y^{3}(\hat{r}_{\sigma}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle\\ \times\langle (\eta',0),0,l'; (0,\eta),0,l||(\lambda_o,\mu_o),k_o,3 \rangle_{\rho_o=1}\Big\{a^{\dagger}_{(\eta',0)\frac{1}{2}}\times \tilde{a}_{(0,\eta)\frac{1}{2}}\Big\}^{\rho_o=1(\lambda_o,\mu_o)k_oL_o=J_o=3}_{\hspace{26mm}M_{J_o}}$$

where $\sigma = \pi, \nu$.

In [1]:
%run rLYL_operator_Expansion.ipynb

# Examples

In [2]:
# Dipole operator test
SU3_rLYL_expansion([5,6], 1)

/tmp/ipykernel_11082/279327973.py:3: DeprecationWarning: Using factorial() with floats is deprecated
  return (-1)**k/math.factorial(abs(k)) * np.sqrt( (2*math.factorial(n)) / (math.gamma(n+l+3/2)) )* (math.gamma(n+l+3/2)) / (math.factorial(n-k)*math.gamma(k+l+3/2))

                                V
etap eta lam_o mu_o K_o
5.0  6.0 0.0   1.0  1.0  2.437578
         1.0   2.0  1.0 -2.465743
         2.0   3.0  1.0 -0.650021
         3.0   4.0  1.0  0.751666
         4.0   5.0  1.0  0.290968
         5.0   6.0  1.0 -0.524549
6.0  5.0 1.0   0.0  1.0  2.437578
         2.0   1.0  1.0 -2.465743
         3.0   2.0  1.0 -0.650021
         4.0   3.0  1.0  0.751666
         5.0   4.0  1.0  0.290968
         6.0   5.0  1.0 -0.524549

In [8]:
# Dipole operator test
SU3_rLYL_expansion([6,7], 1)

/tmp/ipykernel_10960/279327973.py:3: DeprecationWarning: Using factorial() with floats is deprecated
  return (-1)**k/math.factorial(abs(k)) * np.sqrt( (2*math.factorial(n)) / (math.gamma(n+l+3/2)) )* (math.gamma(n+l+3/2)) / (math.factorial(n-k)*math.gamma(k+l+3/2))

                                V
etap eta lam_o mu_o K_o
6.0  7.0 0.0   1.0  1.0  3.056492
         1.0   2.0  1.0 -2.936494
         2.0   3.0  1.0 -0.916947
         3.0   4.0  1.0  0.775914
         4.0   5.0  1.0  0.542103
         5.0   6.0  1.0 -0.345087
         6.0   7.0  1.0 -0.482274
7.0  6.0 1.0   0.0  1.0  3.056492
         2.0   1.0  1.0 -2.936494
         3.0   2.0  1.0 -0.916947
         4.0   3.0  1.0  0.775914
         5.0   4.0  1.0  0.542103
         6.0   5.0  1.0 -0.345087
         7.0   6.0  1.0 -0.482274

In [9]:
# Qudrupole operator test
SU3_rLYL_expansion([5,6], 2)

/tmp/ipykernel_10960/279327973.py:3: DeprecationWarning: Using factorial() with floats is deprecated
  return (-1)**k/math.factorial(abs(k)) * np.sqrt( (2*math.factorial(n)) / (math.gamma(n+l+3/2)) )* (math.gamma(n+l+3/2)) / (math.factorial(n-k)*math.gamma(k+l+3/2))

                                V
etap eta lam_o mu_o K_o
5.0  5.0 1.0   1.0  1.0 -0.479390
         2.0   2.0  1.0  2.991996
                    2.0 -6.131766
         3.0   3.0  1.0 -4.045609
         4.0   4.0  1.0 -1.166248
                    2.0  2.233195
         5.0   5.0  1.0  3.749893
6.0  6.0 1.0   1.0  1.0 -1.933998
         2.0   2.0  1.0  4.323227
                    2.0 -8.859978
         3.0   3.0  1.0 -3.588484
         4.0   4.0  1.0 -2.126495
                    2.0  4.071928
         5.0   5.0  1.0  1.776073
         6.0   6.0  1.0  1.662909
                    2.0 -3.093877

# $r^{3}Y^{3}_\mu(\Omega)$ operators

# Proton operator

The expansion is given by 

$$\left[r_{\pi}^3Y^{3}_\mu(\hat{r}_{\pi})\right]_{\hspace{7mm}M_{J_o}}^{L_o=J_o=3} = \sqrt{\frac{2}{7}}\sum_{(\lambda_o,\mu_o)k_o}\sum_{l,l'}\sum_{\eta=5,\eta'=5}^{6}(-1)^{\eta}\sqrt{2l'+1}\Big\langle \eta',l',\frac{1}{2} \Big|\Big| r_{\pi}^3Y^{3}(\hat{r}_{\pi}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle \\ \times\langle (\eta',0),0,l'; (0,\eta),0,l||(\lambda_o,\mu_o),k_o,3 \rangle_{\rho_o=1}\Big\{a^{\dagger}_{(\eta',0)\frac{1}{2}}\times \tilde{a}_{(0,\eta)\frac{1}{2}}\Big\}^{\rho_o=1(\lambda_o,\mu_o)k_oL_o=J_o=3}_{\hspace{26mm}M_{J_o}}$$

In [8]:
p_r3Y3 = SU3_rLYL_expansion([5,6], 3)
# (0,1) does not contain L=3

/tmp/ipykernel_8574/279327973.py:3: DeprecationWarning: Using factorial() with floats is deprecated
  return (-1)**k/math.factorial(abs(k)) * np.sqrt( (2*math.factorial(n)) / (math.gamma(n+l+3/2)) )* (math.gamma(n+l+3/2)) / (math.factorial(n-k)*math.gamma(k+l+3/2))

In [9]:
p_r3Y3

                                 V
etap eta lam_o mu_o K_o
5.0  6.0 1.0   2.0  1.0   0.267618
         2.0   3.0  1.0  16.065801
                    2.0  -7.160685
         3.0   4.0  1.0  -7.272730
                    2.0  13.101688
         4.0   5.0  1.0  -5.148428
                    2.0   5.869337
         5.0   6.0  1.0   9.751540
                    2.0  -9.977757
6.0  5.0 2.0   1.0  1.0   0.267618
         3.0   2.0  1.0  16.065801
                    2.0  -7.160685
         4.0   3.0  1.0  -7.272730
                    2.0  13.101688
         5.0   4.0  1.0  -5.148428
                    2.0   5.869337
         6.0   5.0  1.0   9.751540
                    2.0  -9.977757

# Neutron operator

The expansion is given by

$$\left[r_{\nu}^3Y^{3}_\mu(\hat{r}_{\nu})\right]_{\hspace{7mm}M_{J_o}}^{L_o=J_o=3} = \sqrt{\frac{2}{7}}\sum_{(\lambda_o,\mu_o)k_o}\sum_{l,l'}\sum_{\eta=6,\eta'=6}^{7}(-1)^{\eta}\sqrt{2l'+1}\Big\langle \eta',l',\frac{1}{2} \Big|\Big| r_{\nu}^3Y^{3}(\hat{r}_{\nu}) \Big|\Big| \eta,l,\frac{1}{2}\Big\rangle \\ \times\langle (\eta',0),0,l'; (0,\eta),0,l||(\lambda_o,\mu_o),k_o,3 \rangle_{\rho_o=1}\Big\{a^{\dagger}_{(\eta',0)\frac{1}{2}}\times \tilde{a}_{(0,\eta)\frac{1}{2}}\Big\}^{\rho_o=1(\lambda_o,\mu_o)k_oL_o=J_o=3}_{\hspace{26mm}M_{J_o}}$$

In [4]:
n_r3Y3 = SU3_rLYL_expansion([6,7], 3)
# (0,1) does not contain L=3

/tmp/ipykernel_11082/279327973.py:3: DeprecationWarning: Using factorial() with floats is deprecated
  return (-1)**k/math.factorial(abs(k)) * np.sqrt( (2*math.factorial(n)) / (math.gamma(n+l+3/2)) )* (math.gamma(n+l+3/2)) / (math.factorial(n-k)*math.gamma(k+l+3/2))

In [6]:
n_r3Y3

                                 V
etap eta lam_o mu_o K_o
6.0  7.0 1.0   2.0  1.0  -5.352645
         2.0   3.0  1.0  22.113754
                    2.0 -14.143197
         3.0   4.0  1.0  -2.677183
                    2.0  15.848214
         4.0   5.0  1.0  -6.615524
                    2.0  15.102062
         5.0   6.0  1.0   1.603821
                    2.0  -8.195877
         6.0   7.0  1.0   2.209156
                    2.0 -16.022495
7.0  6.0 2.0   1.0  1.0  -5.352645
         3.0   2.0  1.0  22.113754
                    2.0 -14.143197
         4.0   3.0  1.0  -2.677183
                    2.0  15.848214
         5.0   4.0  1.0  -6.615524
                    2.0  15.102062
         6.0   5.0  1.0   1.603821
                    2.0  -8.195877
         7.0   6.0  1.0   2.209156
                    2.0 -16.022495