In [1]:
import numpy as np
from sympy.physics.quantum.cg import CG
from sympy.physics.wigner import wigner_9j
%run SU3_implementations.ipynb

In [2]:
# Function to compute the unitary 9-j 
def unitary_9j(j1,j2,j3,j4,j5,j6,j7,j8,j9):
    return float(wigner_9j(j1,j2,j3,j4,j5,j6,j7,j8,j9).doit())*np.sqrt((2*j3+1)*(2*j7+1)*(2*j8+1)*(2*j6+1))

# Function to compute two-shell one-body triple-barred matrix elements from Restrepo, et. al, (2024), ArrXiv 2405.04679
# Arguments:
# bra: [λ'-, μ'-, λ'+, μ'+, ρ', λ', μ', S'-, S'+, S'] 
# ket: [λ-, μ-, λ+, μ+, ρ, λ, μ, S-, S+, S] 
# op: [η', η, λ_o, μ_o, S_o] 
# rhob: Multiplicity of the triple-barred matrix element
# ========> NOTE: The ρ labels must start in 0, as ρ = 0,1,2,...

def ts_ob_matrix_element(bra, ket, op, rhob):
    
    # Extract the labels   
    lm, mm, lp, mp, rho, l, m, Sm, Sp, S = ket
    lmq, mmq, lpq, mpq, rhoq, lq, mq, Smq, Spq, Sq = bra
    etaq, eta, lo, mo, So = op
    
    # Algebraic coefficient
    coeff = (-1)**(eta+1/2+Sp+Spq+lpq-lp+mpq-mp)*np.sqrt( SU3dim(lp, mp) / SU3dim(lpq, mpq) )*np.sqrt( (2*Sp + 1)/(2*Spq + 1) )
    
    # Compute the unitary 9-j spin coefficient
    coeff_9j = unitary_9j(Sm, 1/2, Smq, Sp, 1/2, Spq, S, So, Sq)
    
    # Compute 9-(λ,μ) coefficient involved
    SU3Coeffs9lammu = SU39lammu(lm, mm, etaq, 0  , lmq, mmq,
                                lp, mp, 0   , eta, lpq, mpq,
                                l , m , lo  , mo , lq , mq )  
    
    # Filter 9-(λ,μ) coefficients by the values of ρ
    SU3Coeffs9lammuFilter = SU3Coeffs9lammu[(SU3Coeffs9lammu["rho13"] == rho) & (SU3Coeffs9lammu["rho1234"] == rhoq) & (SU3Coeffs9lammu["rho1324"] == rhob)]
            
        
    # MISSSING IMPLEMENTATION OF MATRIX ELEMENTS ==================================================
    # MISSSING IMPLEMENTATION OF MATRIX ELEMENTS ==================================================
    # MISSSING IMPLEMENTATION OF MATRIX ELEMENTS ==================================================
    
    return coeff*coeff_9j*float(SU3Coeffs9lammuFilter["value"])    

# Function to compute double barred matrix element of neutron-proton operator from Troltenier, et. al, (1995), Nuc. Phys. A
# Arguments:
# bra: [λ'_π, μ'_π, λ'_ν, μ'_ν, ρ', λ', μ', K', L', S'_π, S'_ν, S', J'] 
# ket: [λ_π, μ_π, λ_ν, μ_ν, ρ, λ, μ, K, L, S_π, S_ν, S, J] 
# op: [λ_πo, μ_πo, λ_νo, μ_νo, ρ_o, λ_o, μ_o, K_o, L_o, S_πo, S_νo, S_o, J_o] 
# ========> NOTE: The K labels must start in 1, as K = 1,2,3,...
# ========> NOTE: The ρ labels must start in 0, as ρ = 0,1,2,...

def db_matrix_element(bra, ket, op):
    
    # Extract the labels
    lp, mp, ln, mn, rho, l, m, k, L, Sp, Sn, S, J = ket
    lpq, mpq, lnq, mnq, rhoq, lq, mq, kq, Lq, Spq, Snq, Sq, Jq = bra
    lpo, mpo, lno, mno, rhoo, lo, mo, ko, Lo, Spo, Sno, So, Jo = op

    # Compute the two unitary 9-j coefficients
    coeff_9j_1 = unitary_9j(L, Lo, Lq, S, So, Sq, J, Jo, Jq)
    coeff_9j_2 = unitary_9j(Sp, Spo, Spq, Sn, Sno, Snq, S, So, Sq)
    
    # Compute all Wigner coefficients involved
    SU3Coeffs = SU3WignerCoeff(l, m, L, lo, mo, Lo, lq, mq, Lq) 
    
    # Filter over K, K' and Ko
    SU3CoeffsKFilter = SU3Coeffs[(SU3Coeffs["k1"] == k) & (SU3Coeffs["k2"] == ko) & (SU3Coeffs["k3"] == kq)]
    
    # Compute all 9-(λ,μ) coefficients involved
    SU3Coeffs9lammu = SU39lammu(lp, mp, lpo, mpo, lpq, mpq,
                                ln, mn, lno, mno, lnq, mnq,
                                l , m , lo , mo , lq , mq )    
    
    # FILTER OVER THE RHOOOOSSSS ==================================================
    # FILTER OVER THE RHOOOOSSSS ==================================================
    # FILTER OVER THE RHOOOOSSSS ==================================================
    
    #display(SU3Coeffs)
    display(SU3Coeffs9lammu)
    
    return SU3CoeffsKFilter

In [3]:
# bra: [λ'-, μ'-, λ'+, μ'+, ρ', λ', μ', S'-, S'+, S'] 
# ket: [λ-, μ-, λ+, μ+, ρ, λ, μ, S-, S+, S] 
# op: [η', η, λ_o, μ_o, S_o] 
# rhob: Multiplicity of the triple-barred matrix element
# ========> NOTE: The ρ labels must start in 0, as ρ = 0,1,2,...

b = ts_ob_matrix_element([34,4,0,0,0,34,4,0,0,0], [32,2,7,0,0,39,2,1/2,1/2,0], [6,7,3,4,0], 0)

In [4]:
a = db_matrix_element([26,4,34,4,1,60,8,1,4,0,0,0,4], [31,2,34,4,1,65,6,1,3,0,0,0,3], [4,5,0,0,1,4,5,1,1,0,0,0,1])

   rho1324  rho24  rho13  rho1234  rho34  rho12     value
0        0      0      0        0      0      0  0.793606
1        0      0      0        0      0      1 -0.012739
2        0      0      0        0      0      2 -0.000057
3        1      0      0        0      0      0 -0.019199
4        1      0      0        0      0      1  0.616138
5        1      0      0        0      0      2 -0.009771
6        2      0      0        0      0      0 -0.000958
7        2      0      0        0      0      1 -0.034951
8        2      0      0        0      0      2  0.366610

In [5]:
a

   k1  L1  k2  L2  k3  L3      rho1     rho2      rho3
0   1   3   1   1   1   4  0.153704 -0.00361  0.115282

In [6]:
SU3rme([[2,2,2,2],26,4],[[2,2,2,1],25,2],5)

-1.6451950239